"""initial schema

Revision ID: 88274ac9404f
Revises:
Create Date: 2026-09-09 22:14:04.022382

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "88274ac9404f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "restaurants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("area", sa.String(length=80), nullable=False),
        sa.Column("cuisine_tags", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("restaurants", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_restaurants_area"), ["area"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column(
            "gender",
            sa.Enum("MALE", "FEMALE", "OTHER", name="gender", native_enum=False, length=16),
            nullable=True,
        ),
        sa.Column("area", sa.String(length=80), nullable=True),
        sa.Column("spice_tolerance", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("age IS NULL OR age BETWEEN 10 AND 120", name="ck_users_age"),
        sa.CheckConstraint("spice_tolerance BETWEEN 0 AND 5", name="ck_users_spice_tolerance"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_area"), ["area"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "food_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("restaurant_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("cuisine", sa.String(length=60), nullable=False),
        sa.Column("spice_level", sa.Integer(), nullable=False),
        sa.Column("is_veg", sa.Boolean(), nullable=False),
        sa.Column("is_rice_based", sa.Boolean(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("prep_time_min", sa.Integer(), nullable=False),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("ingredient_tags", sa.JSON(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("price >= 0", name="ck_food_items_price"),
        sa.CheckConstraint("spice_level BETWEEN 0 AND 5", name="ck_food_items_spice_level"),
        sa.ForeignKeyConstraint(["restaurant_id"], ["restaurants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("food_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_food_items_cuisine"), ["cuisine"], unique=False)
        batch_op.create_index(
            "ix_food_items_cuisine_available", ["cuisine", "is_available"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_food_items_is_available"), ["is_available"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_food_items_restaurant_id"), ["restaurant_id"], unique=False
        )

    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "CONFIRMED",
                "PREPARING",
                "DELIVERED",
                "CANCELLED",
                name="orderstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.create_index("ix_orders_user_created", ["user_id", "created_at"], unique=False)

    op.create_table(
        "impressions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("food_item_id", sa.Integer(), nullable=False),
        sa.Column("was_ordered", sa.Boolean(), nullable=False),
        sa.Column("shown_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["food_item_id"], ["food_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("impressions", schema=None) as batch_op:
        batch_op.create_index("ix_impressions_item", ["food_item_id"], unique=False)
        batch_op.create_index("ix_impressions_user_shown", ["user_id", "shown_at"], unique=False)

    op.create_table(
        "item_neighbors",
        sa.Column("food_item_id", sa.Integer(), nullable=False),
        sa.Column("neighbor_id", sa.Integer(), nullable=False),
        sa.Column("distance", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.CheckConstraint("food_item_id <> neighbor_id", name="ck_item_neighbors_not_self"),
        sa.ForeignKeyConstraint(["food_item_id"], ["food_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["neighbor_id"], ["food_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("food_item_id", "neighbor_id"),
    )
    with op.batch_alter_table("item_neighbors", schema=None) as batch_op:
        batch_op.create_index("ix_item_neighbors_item_rank", ["food_item_id", "rank"], unique=False)

    op.create_table(
        "order_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("food_item_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.CheckConstraint("quantity > 0", name="ck_order_items_quantity"),
        sa.ForeignKeyConstraint(["food_item_id"], ["food_items.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_order_items_food_item_id"), ["food_item_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_order_items_order_id"), ["order_id"], unique=False)

    op.create_table(
        "ratings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("food_item_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Numeric(precision=2, scale=1), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("rating BETWEEN 1 AND 5", name="ck_ratings_range"),
        sa.ForeignKeyConstraint(["food_item_id"], ["food_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "food_item_id", name="uq_ratings_user_item"),
    )
    with op.batch_alter_table("ratings", schema=None) as batch_op:
        batch_op.create_index("ix_ratings_item", ["food_item_id"], unique=False)
        batch_op.create_index("ix_ratings_user_created", ["user_id", "created_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ratings", schema=None) as batch_op:
        batch_op.drop_index("ix_ratings_user_created")
        batch_op.drop_index("ix_ratings_item")

    op.drop_table("ratings")
    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_order_items_order_id"))
        batch_op.drop_index(batch_op.f("ix_order_items_food_item_id"))

    op.drop_table("order_items")
    with op.batch_alter_table("item_neighbors", schema=None) as batch_op:
        batch_op.drop_index("ix_item_neighbors_item_rank")

    op.drop_table("item_neighbors")
    with op.batch_alter_table("impressions", schema=None) as batch_op:
        batch_op.drop_index("ix_impressions_user_shown")
        batch_op.drop_index("ix_impressions_item")

    op.drop_table("impressions")
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_index("ix_orders_user_created")

    op.drop_table("orders")
    with op.batch_alter_table("food_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_food_items_restaurant_id"))
        batch_op.drop_index(batch_op.f("ix_food_items_is_available"))
        batch_op.drop_index("ix_food_items_cuisine_available")
        batch_op.drop_index(batch_op.f("ix_food_items_cuisine"))

    op.drop_table("food_items")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))
        batch_op.drop_index(batch_op.f("ix_users_area"))

    op.drop_table("users")
    with op.batch_alter_table("restaurants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_restaurants_area"))

    op.drop_table("restaurants")
    # ### end Alembic commands ###
